#define ID_TEXTAREA 89
#define ID_ADD_TEXT 90
#define ID_SET_IP_ADDRESS 91
#define ID_CONNECT 92
#define ID_DISCONNECT 93
#define ID_ENTER_TEXT_BOX 94
#define ID_ERR_CONNECT_LABEL 95
#define ID_SET_USERNAME 96